version: '1'
services:
  backend:
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
